print("Ingresa el número: ")
n = input()
numN = int(n)

print("{} x 1 = {}".format(n, numN))
print("{} x 2 = {}".format(n, numN*2))
print("{} x 3 = {}".format(n, numN*3))
print("{} x 4 = {}".format(n, numN*4))
print("{} x 5 = {}".format(n, numN*5))
print("{} x 6 = {}".format(n, numN*6))
print("{} x 7 = {}".format(n, numN*7))
print("{} x 8 = {}".format(n, numN*8))
print("{} x 9 = {}".format(n, numN*9))
print("{} x 10 = {}".format(n, numN*10))